/*
 * ESP32-S3 rtc control
 *
 * Copyright (c) 2024 Espressif Systems (Shanghai) Co. Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 or
 * (at your option) any later version.
 */

#pragma once

#include "hw/hw.h"
#include "hw/sysbus.h"
#include "hw/registerfields.h"
#include "hw/misc/esp32s3_reg.h"

#define TYPE_ESP32S3_RTC_CNTL "misc.esp32s3.rtc_cntl"
#define ESP32S3_RTC_CNTL(obj) OBJECT_CHECK(Esp32s3RtcCntlState, (obj), TYPE_ESP32S3_RTC_CNTL)

#define ESP32S3_RTC_DIG_RESET_GPIO    "dig-reset"
#define ESP32S3_RTC_CPU_RESET_GPIO    "cpu-reset"
#define ESP32S3_RTC_CPU_STALL_GPIO    "cpu-stall"
#define ESP32S3_RTC_LIGHT_SLEEP_GPIO  "light-sleep"

typedef enum Esp32s3ResetCause {
    ESP32_POWERON_RESET = 1,
    ESP32_SW_SYS_RESET = 3,
    ESP32_OWDT_RESET = 4,
    ESP32_DEEPSLEEP_RESET = 5,
    ESP32_SDIO_RESET = 6,
    ESP32_TG0WDT_SYS_RESET = 7,
    ESP32_TG1WDT_SYS_RESET = 8,
    ESP32_RTCWDT_SYS_RESET = 9,
    ESP32_TGWDT_CPU_RESET = 11,
    ESP32_SW_CPU_RESET = 12,
    ESP32_RTCWDT_CPU_RESET = 13,
    ESP32_EXT_CPU_RESET = 14,
    ESP32_RTCWDT_BROWN_OUT_RESET = 15,
    ESP32_RTCWDT_RTC_RESET = 16
} Esp32s3ResetCause;

typedef enum Esp32s3FastClkSel {
    ESP32_FAST_CLK_XTALD4 = 0,
    ESP32_FAST_CLK_8M = 1
} Esp32s3FastClkSel;

typedef enum Esp32s3SlowClkSel {
    ESP32_SLOW_CLK_RC = 0,
    ESP32_SLOW_CLK_32KXTAL = 1,
    ESP32_SLOW_CLK_8MD256 = 2
} Esp32s3SlowClkSel;

typedef enum Esp32s3RtcSleepState {
    ESP32S3_RTC_SLEEP_AWAKE = 0,
    ESP32S3_RTC_SLEEP_REQUESTED,
    ESP32S3_RTC_SLEEP_SLEEPING,
    ESP32S3_RTC_SLEEP_REJECTED,
    ESP32S3_RTC_SLEEP_WOKE,
} Esp32s3RtcSleepState;

typedef struct Esp32s3RtcCntlState {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    qemu_irq irq;
    qemu_irq dig_reset_req;
    qemu_irq cpu_reset_req[ESP32S3_CPU_COUNT];
    qemu_irq cpu_stall_req[ESP32S3_CPU_COUNT];
    qemu_irq light_sleep_req;
    bool cpu_stall_state[ESP32S3_CPU_COUNT];

    uint32_t xtal_apb_freq;
    uint32_t pll_apb_freq;
    Esp32s3FastClkSel rtc_fastclk;
    uint32_t rtc_fastclk_freq;
    Esp32s3SlowClkSel rtc_slowclk;
    uint32_t rtc_slowclk_freq;
    int64_t time_base_ns;

    uint32_t options0_reg;
    uint32_t time_update_reg;
    uint64_t time_reg[2];
    uint32_t sw_cpu_stall_reg;
    uint32_t timer2_reg;
    uint32_t timer1_reg;
    uint32_t clk_conf_reg;
    uint32_t sdio_conf_reg;
    uint32_t rtc_reg;
    uint32_t pwc_reg;
    uint32_t bias_conf_reg;
    uint32_t regulator_drv_ctrl_reg;
    uint32_t dig_pwc_reg;
    uint32_t scratch_reg[ESP32S3_RTC_CNTL_SCRATCH_REG_COUNT];
    Esp32s3ResetCause reset_cause[ESP32S3_CPU_COUNT];
    bool stat_vector_sel[ESP32S3_CPU_COUNT];

    /* Sleep state machine */
    Esp32s3RtcSleepState sleep_state;
    uint32_t slp_timer0;
    uint32_t slp_timer1;
    uint32_t wakeup_state;
    uint32_t slp_reject_conf;
    uint32_t ext_wakeup_conf;
    uint32_t ext_wakeup1;
    uint32_t ext_wakeup1_status;
    uint32_t int_raw;
    uint32_t slp_wakeup_cause;
    QEMUTimer slp_timer;
    uint32_t wdt_wprotect;
    uint32_t swd_conf;
    uint32_t swd_wprotect;
    uint32_t pad_hold;
    uint32_t dig_pad_hold;
    uint32_t date_reg;

    /* GPIO model reference for wakeup pin checking */
    struct ESP32S3GPIOState *gpio;
} Esp32s3RtcCntlState;

/* Called by GPIO model when a wakeup-configured pin triggers */
void esp32s3_rtc_gpio_wakeup_notify(Esp32s3RtcCntlState *s, int gpio_num);
void esp32s3_rtc_notify_system_reset(Esp32s3RtcCntlState *s);

REG32(RTC_CNTL_OPTIONS0, 0x00)
    FIELD(RTC_CNTL_OPTIONS0, SW_SYS_RESET, 31, 1)
    FIELD(RTC_CNTL_OPTIONS0, XTL_FORCE_PU, 13, 1)
    FIELD(RTC_CNTL_OPTIONS0, BBPLL_FORCE_PU, 11, 1)
    FIELD(RTC_CNTL_OPTIONS0, BBPLL_I2C_FORCE_PU, 9, 1)
    FIELD(RTC_CNTL_OPTIONS0, BB_I2C_FORCE_PU, 7, 1)
    FIELD(RTC_CNTL_OPTIONS0, SW_PROCPU_RESET, 5, 1)
    FIELD(RTC_CNTL_OPTIONS0, SW_APPCPU_RESET, 4, 1)
    FIELD(RTC_CNTL_OPTIONS0, SW_STALL_PROCPU_C0, 2, 2)
    FIELD(RTC_CNTL_OPTIONS0, SW_STALL_APPCPU_C0, 0, 2)

REG32(RTC_CNTL_TIMER2, 0x20)
    FIELD(RTC_CNTL_TIMER2, ULPCP_TOUCH_START_WAIT, 15, 9)

REG32(RTC_CNTL_TIME_UPDATE, 0xc)
    FIELD(RTC_CNTL_TIME_UPDATE, UPDATE, 31, 1)
    FIELD(RTC_CNTL_TIME_UPDATE, VALID, 30, 1)
    FIELD(RTC_CNTL_TIME_UPDATE, TIMER_SYS_RST, 29, 1)
    FIELD(RTC_CNTL_TIME_UPDATE, TIMER_XTL_OFF, 28, 1)
    FIELD(RTC_CNTL_TIME_UPDATE, TIMER_SYS_STALL, 27, 1)
REG32(RTC_CNTL_TIME0, 0x10)
REG32(RTC_CNTL_TIME1, 0x14)
REG32(RTC_CNTL_TIMER1, 0x1c)
    FIELD(RTC_CNTL_TIMER1, PLL_BUF_WAIT, 24, 8)
    FIELD(RTC_CNTL_TIMER1, XTL_BUF_WAIT, 14, 10)
    FIELD(RTC_CNTL_TIMER1, CK8M_WAIT, 6, 8)

REG32(RTC_CNTL_RESET_STATE, 0x38)
    FIELD(RTC_CNTL_RESET_STATE, PROCPU_STAT_VECTOR_SEL, 13, 1)
    FIELD(RTC_CNTL_RESET_STATE, APPCPU_STAT_VECTOR_SEL, 12, 1)
    FIELD(RTC_CNTL_RESET_STATE, RESET_CAUSE_APPCPU, 6, 6)
    FIELD(RTC_CNTL_RESET_STATE, RESET_CAUSE_PROCPU, 0, 6)

REG32(RTC_CNTL_STORE0, 0x50)
REG32(RTC_CNTL_STORE1, 0x54)
REG32(RTC_CNTL_STORE2, 0x58)
REG32(RTC_CNTL_STORE3, 0x5c)

REG32(RTC_CNTL_CLK_CONF, 0x74)
    FIELD(RTC_CNTL_CLK_CONF, ANA_CLK_RTC_SEL, 30, 2)
    FIELD(RTC_CNTL_CLK_CONF, FAST_CLK_RTC_SEL, 29, 1)
    FIELD(RTC_CNTL_CLK_CONF, XTAL_GLOBAL_FORCE_NOGATING, 28, 1)
    FIELD(RTC_CNTL_CLK_CONF, XTAL_GLOBAL_FORCE_GATING, 27, 1)
    FIELD(RTC_CNTL_CLK_CONF, CK8M_FORCE_PU, 26, 1)
    FIELD(RTC_CNTL_CLK_CONF, CK8M_FORCE_PD, 25, 1)
    FIELD(RTC_CNTL_CLK_CONF, CK8M_DFREQ, 17, 8)
    FIELD(RTC_CNTL_CLK_CONF, CK8M_FORCE_NOGATING, 16, 1)
    FIELD(RTC_CNTL_CLK_CONF, XTAL_FORCE_NOGATING, 15, 1)
    FIELD(RTC_CNTL_CLK_CONF, CK8M_DIV_SEL, 12, 3)
    FIELD(RTC_CNTL_CLK_CONF, DIG_CLK8M_EN, 10, 1)
    FIELD(RTC_CNTL_CLK_CONF, DIG_CLK8M_D256_EN, 9, 1)
    FIELD(RTC_CNTL_CLK_CONF, DIG_XTAL32K_EN, 8, 1)
    FIELD(RTC_CNTL_CLK_CONF, ENB_CK8M_DIV, 7, 1)
    FIELD(RTC_CNTL_CLK_CONF, ENB_CK8M, 6, 1)
    FIELD(RTC_CNTL_CLK_CONF, CK8M_DIV, 4, 2)
    FIELD(RTC_CNTL_CLK_CONF, CK8M_DIV_SEL_VLD, 3, 1)
    FIELD(RTC_CNTL_CLK_CONF, EFUSE_CLK_FORCE_NOGATING, 2, 1)
    FIELD(RTC_CNTL_CLK_CONF, EFUSE_CLK_FORCE_GATING, 1, 1)

REG32(RTC_CNTL_SDIO_CONF, 0x7c)
    FIELD(RTC_CNTL_SDIO_CONF, XPD_SDIO_REG, 31, 1)
    FIELD(RTC_CNTL_SDIO_CONF, DREFH_SDIO, 29, 2)
    FIELD(RTC_CNTL_SDIO_CONF, DREFM_SDIO, 27, 2)
    FIELD(RTC_CNTL_SDIO_CONF, DREFL_SDIO, 25, 2)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_TIEH, 23, 1)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_FORCE, 22, 1)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_PD_EN, 21, 1)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_ENCURLIM, 20, 1)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_MODECURLIM, 19, 1)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_DCURLIM, 16, 3)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_EN_INITI, 15, 1)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_INITI, 13, 2)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_DCAP, 11, 2)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_DTHDRV, 9, 2)
    FIELD(RTC_CNTL_SDIO_CONF, SDIO_TIMER_TARGET, 0, 8)

REG32(RTC_CNTL_RTC, 0x84)
    FIELD(RTC_CNTL_RTC, REGULATOR_FORCE_PU, 31, 1)

REG32(RTC_CNTL_PWC, 0x88)
    FIELD(RTC_CNTL_PWC, PAD_FORCE_HOLD, 21, 1)
    FIELD(RTC_CNTL_PWC, PD_EN, 20, 1)
    FIELD(RTC_CNTL_PWC, FORCE_PU, 19, 1)
    FIELD(RTC_CNTL_PWC, FORCE_PD, 18, 1)
    FIELD(RTC_CNTL_PWC, SLOWMEM_FORCE_LPU, 11, 1)
    FIELD(RTC_CNTL_PWC, FASTMEM_FORCE_LPU, 8, 1)

REG32(RTC_CNTL_BIAS_CONF, 0x80)
    FIELD(RTC_CNTL_BIAS_CONF, DBG_ATTEN_WAKEUP, 26, 4)
    FIELD(RTC_CNTL_BIAS_CONF, DBG_ATTEN_MONITOR, 22, 4)
    FIELD(RTC_CNTL_BIAS_CONF, DBG_ATTEN_DEEP_SLP, 18, 4)
    FIELD(RTC_CNTL_BIAS_CONF, BIAS_SLEEP_MONITOR, 17, 1)
    FIELD(RTC_CNTL_BIAS_CONF, BIAS_SLEEP_DEEP_SLP, 16, 1)
    FIELD(RTC_CNTL_BIAS_CONF, PD_CUR_MONITOR, 15, 1)
    FIELD(RTC_CNTL_BIAS_CONF, PD_CUR_DEEP_SLP, 14, 1)

REG32(RTC_CNTL_REGULATOR_DRV_CTRL, 0x8c)
    FIELD(RTC_CNTL_REGULATOR_DRV_CTRL, DG_VDD_DRV_B_SLP, 12, 8)

REG32(RTC_CNTL_DIG_PWC, 0x90)
    FIELD(RTC_CNTL_DIG_PWC, DG_WRAP_PD_EN, 31, 1)
    FIELD(RTC_CNTL_DIG_PWC, WIFI_PD_EN, 30, 1)
    FIELD(RTC_CNTL_DIG_PWC, CPU_TOP_PD_EN, 29, 1)
    FIELD(RTC_CNTL_DIG_PWC, DG_PERI_PD_EN, 28, 1)
    FIELD(RTC_CNTL_DIG_PWC, WIFI_FORCE_PU, 18, 1)
    FIELD(RTC_CNTL_DIG_PWC, LSLP_MEM_FORCE_PU, 4, 1)

REG32(RTC_CNTL_SW_CPU_STALL, 0xbc)
    FIELD(RTC_CNTL_SW_CPU_STALL, PROCPU_C1, 26, 6)
    FIELD(RTC_CNTL_SW_CPU_STALL, APPCPU_C1, 20, 6)

REG32(RTC_CNTL_STORE4, 0xc0)
REG32(RTC_CNTL_STORE5, 0xc4)
REG32(RTC_CNTL_STORE6, 0xc8)
REG32(RTC_CNTL_STORE7, 0xcc)
REG32(RTC_CNTL_TIME_LOW1, 0xec)
REG32(RTC_CNTL_TIME_HIGH1, 0xf0)
REG32(RTC_CNTL_DATE,   0x1fc)
    FIELD(RTC_CNTL_DATE, DATE, 0, 28)

/* Sleep/wake registers */
REG32(RTC_CNTL_SLP_TIMER0, 0x04)
REG32(RTC_CNTL_SLP_TIMER1, 0x08)
    FIELD(RTC_CNTL_SLP_TIMER1, MAIN_TIMER_ALARM_EN, 16, 1)
    FIELD(RTC_CNTL_SLP_TIMER1, SLP_VAL_HI, 0, 16)

REG32(RTC_CNTL_STATE0, 0x18)
    FIELD(RTC_CNTL_STATE0, SLEEP_EN, 31, 1)
    FIELD(RTC_CNTL_STATE0, SLP_REJECT, 30, 1)
    FIELD(RTC_CNTL_STATE0, SLP_WAKEUP, 29, 1)
    FIELD(RTC_CNTL_STATE0, SLP_REJECT_CAUSE_CLR, 1, 1)

REG32(RTC_CNTL_WAKEUP_STATE, 0x3c)
    FIELD(RTC_CNTL_WAKEUP_STATE, WAKEUP_ENA, 15, 17)
    FIELD(RTC_CNTL_WAKEUP_STATE, GPIO_WAKEUP_EN, 17, 1)
    FIELD(RTC_CNTL_WAKEUP_STATE, TIMER_WAKEUP_EN, 18, 1)

REG32(RTC_CNTL_INT_RAW, 0x44)
    FIELD(RTC_CNTL_INT_RAW, SLP_WAKEUP, 0, 1)
    FIELD(RTC_CNTL_INT_RAW, SLP_REJECT, 1, 1)

REG32(RTC_CNTL_INT_CLR, 0x4c)

REG32(RTC_CNTL_SLP_REJECT_CONF, 0x68)
    FIELD(RTC_CNTL_SLP_REJECT_CONF, DEEP_SLP_REJECT_EN, 31, 1)
    FIELD(RTC_CNTL_SLP_REJECT_CONF, LIGHT_SLP_REJECT_EN, 30, 1)
    FIELD(RTC_CNTL_SLP_REJECT_CONF, SLEEP_REJECT_ENA, 12, 18)

REG32(RTC_CNTL_EXT_WAKEUP_CONF, 0x64)
    FIELD(RTC_CNTL_EXT_WAKEUP_CONF, EXT_WAKEUP1_LV, 31, 1)
    FIELD(RTC_CNTL_EXT_WAKEUP_CONF, EXT_WAKEUP0_LV, 30, 1)
    FIELD(RTC_CNTL_EXT_WAKEUP_CONF, GPIO_WAKEUP_FILTER, 29, 1)

REG32(RTC_CNTL_EXT_WAKEUP1, 0xe0)
    FIELD(RTC_CNTL_EXT_WAKEUP1, EXT_WAKEUP1_STATUS_CLR, 22, 1)
    FIELD(RTC_CNTL_EXT_WAKEUP1, EXT_WAKEUP1_SEL, 0, 22)

REG32(RTC_CNTL_EXT_WAKEUP1_STATUS, 0xe4)
    FIELD(RTC_CNTL_EXT_WAKEUP1_STATUS, EXT_WAKEUP1_STATUS, 0, 22)

REG32(RTC_CNTL_SLP_WAKEUP_CAUSE, 0x130)
    FIELD(RTC_CNTL_SLP_WAKEUP_CAUSE, EXT1, 1, 1)
    FIELD(RTC_CNTL_SLP_WAKEUP_CAUSE, GPIO, 2, 1)
    FIELD(RTC_CNTL_SLP_WAKEUP_CAUSE, TIMER, 3, 1)

/* WDT write-protect registers */
REG32(RTC_CNTL_WDTWPROTECT, 0xb0)
REG32(RTC_CNTL_SWD_CONF, 0xb4)
    FIELD(RTC_CNTL_SWD_CONF, SWD_AUTO_FEED_EN, 31, 1)
    FIELD(RTC_CNTL_SWD_CONF, SWD_DISABLE, 30, 1)
    FIELD(RTC_CNTL_SWD_CONF, SWD_FEED, 29, 1)
REG32(RTC_CNTL_SWD_WPROTECT, 0xb8)

/* Pad hold registers */
REG32(RTC_CNTL_PAD_HOLD, 0xd8)
    FIELD(RTC_CNTL_PAD_HOLD, PAD_HOLD, 0, 22)
REG32(RTC_CNTL_DIG_PAD_HOLD, 0xdc)

#define ESP32S3_RTC_CNTL_SIZE (A_RTC_CNTL_DATE + 4)
#define ESP32S3_RTC_CNTL_DATE_RESET 0x02101271
